{{- if and .Values.sentry.dsn (not .Values.sentry.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-sentry-events.fullname" . }}
  labels:
    {{- include "kube-sentry-events.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
{{- end }}
